# Generated by Django 4.2 on 2023-04-17 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class_Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('1', 'الأول ابتدائي'), ('2', 'الثاني ابتدائي'), ('3', 'الثالث ابتدائي'), ('4', 'الرابع ابتدائي'), ('5', 'الخامس ابتدائي'), ('6', 'السادس ابتدائي'), ('7', 'الأول متوسط'), ('8', 'الثاني متوسط'), ('9', 'الثالث متوسط'), ('10', 'الأول ثانوي'), ('11', 'الثاني ثانوي'), ('12', 'الثالث ثانوي')], max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(choices=[('1', 'قران'), ('2', 'تربية اسلامية'), ('3', 'لغتي'), ('4', 'رياضيات'), ('5', 'علوم'), ('6', 'تربية بدنية'), ('7', 'تربية فنية'), ('8', 'لغة انجليزية'), ('9', 'اجتماعيات'), ('10', 'مهارات حيايتة وأسرية'), ('11', 'التربية الرقمية')], max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='student_class',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='app.class_name'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='class_teaching',
            field=models.ManyToManyField(to='app.class_name'),
        ),
    ]
