# Generated by Django 4.2 on 2023-04-17 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_teacher_class_teaching_teacher_class_teaching'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_class',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='app.class_name'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='class_teaching',
            field=models.ManyToManyField(to='app.class_name'),
        ),
    ]
