# Generated by Django 4.2 on 2023-04-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_student_student_class_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('1', 'الأول ابتدائي'), ('2', 'الثاني ابتدائي'), ('3', 'الثالث ابتدائي'), ('4', 'الرابع ابتدائي'), ('5', 'الخامس ابتدائي'), ('6', 'السادس ابتدائي'), ('7', 'الأول متوسط'), ('8', 'الثاني متوسط'), ('9', 'الثالث متوسط'), ('10', 'الأول ثانوي'), ('11', 'الثاني ثانوي'), ('12', 'الثالث ثانوي')], max_length=150)),
                ('section', models.CharField(choices=[('A', 'أ'), ('B', 'ب'), ('C', 'ج'), ('D', 'د')], max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_class',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='level',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='student',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='class_teaching',
        ),
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Class_Name',
        ),
        migrations.AddField(
            model_name='classes',
            name='student',
            field=models.ManyToManyField(to='app.student'),
        ),
        migrations.AddField(
            model_name='classes',
            name='subject',
            field=models.ManyToManyField(to='app.subject'),
        ),
    ]
