# Generated by Django 4.2 on 2023-04-17 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_classes_remove_student_student_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(choices=[('Quran', 'قران'), ('Islamic', 'تربية اسلامية'), ('My Language', 'لغتي'), ('Math', 'رياضيات'), ('Science', 'علوم'), ('Sports', 'تربية بدنية'), ('Art', 'تربية فنية'), ('English', 'لغة انجليزية'), ('Geographic', 'اجتماعيات'), ('Live&Family', 'مهارات حيايتة وأسرية'), ('Digital', 'التربية الرقمية')], max_length=255),
        ),
        migrations.RemoveField(
            model_name='subject',
            name='teacher',
        ),
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.ManyToManyField(to='app.teacher'),
        ),
    ]
