# Generated by Django 4.2 on 2023-04-17 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_teacher_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='subject',
        ),
        migrations.AddField(
            model_name='course',
            name='which_class',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.classes'),
        ),
    ]
