# Generated by Django 4.2 on 2023-04-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_course_subject_course_which_class'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'الدرس', 'verbose_name_plural': 'الدروس'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'الطالب', 'verbose_name_plural': 'الطلاب'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'المادة الدراسية', 'verbose_name_plural': 'المواد الدراسية'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'المعلم', 'verbose_name_plural': 'المعلمون'},
        ),
        migrations.AddField(
            model_name='teacher',
            name='major',
            field=models.CharField(choices=[('Quran', 'قران'), ('Islamic', 'تربية اسلامية'), ('My Language', 'لغتي'), ('Math', 'رياضيات'), ('Science', 'علوم'), ('Sports', 'تربية بدنية'), ('Art', 'تربية فنية'), ('English', 'لغة انجليزية'), ('Geographic', 'اجتماعيات'), ('Live&Family', 'مهارات حيايتة وأسرية'), ('Digital', 'التربية الرقمية')], max_length=100, null=True),
        ),
    ]
