# Generated by Django 4.2 on 2023-04-18 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_subject_name_alter_teacher_major'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='subject',
        ),
        migrations.AddField(
            model_name='classes',
            name='subject',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.subject'),
        ),
    ]
