# Generated by Django 4.2 on 2023-04-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_classes_subject_classes_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='name',
            field=models.CharField(choices=[('الأول ابتدائي', 'الأول ابتدائي'), ('الثاني ابتدائي', 'الثاني ابتدائي'), ('الثالث ابتدائي', 'الثالث ابتدائي'), ('الرابع ابتدائي', 'الرابع ابتدائي'), ('الخامس ابتدائي', 'الخامس ابتدائي'), ('السادس ابتدائي', 'السادس ابتدائي'), ('الأول متوسط', 'الأول متوسط'), ('الثاني متوسط', 'الثاني متوسط'), ('الثالث متوسط', 'الثالث متوسط'), ('الأول ثانوي', 'الأول ثانوي'), ('الثاني ثانوي', 'الثاني ثانوي'), ('الثالث ثانوي', 'الثالث ثانوي')], max_length=150),
        ),
        migrations.AlterField(
            model_name='classes',
            name='section',
            field=models.CharField(choices=[('أ', 'أ'), ('ب', 'ب'), ('ج', 'ج'), ('د', 'د')], max_length=2),
        ),
    ]
