# Generated by Django 4.2 on 2023-04-18 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_classes_name_alter_classes_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='subject',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.subject'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
