# Generated by Django 4.2 on 2023-04-18 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_classes_subject_alter_teacher_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='subject',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.subject'),
        ),
    ]
