# Generated by Django 4.2 on 2023-04-18 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_classes_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classes',
            old_name='student',
            new_name='students',
        ),
    ]
