# Generated by Django 4.2 on 2023-04-18 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_classes_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'المستخدم', 'verbose_name_plural': 'المستخدمون'},
        ),
    ]
