# Generated by Django 3.2.17 on 2023-04-19 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='students',
            field=models.ManyToManyField(db_column='StudentsColumns', to='app.Student'),
        ),
    ]
