# Generated by Django 3.2.17 on 2023-04-19 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_classes_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='students',
            field=models.ManyToManyField(related_name='classes', to='app.Student'),
        ),
    ]
