# Generated by Django 3.2.17 on 2023-04-20 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_assignment_grade_semester'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semester',
            options={'verbose_name': 'الفصل الدراسي', 'verbose_name_plural': 'الفصول الدراسية'},
        ),
    ]
