# Generated by Django 3.2.17 on 2023-04-20 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_semester_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.subject'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.teacher'),
        ),
        migrations.AddField(
            model_name='subject',
            name='code',
            field=models.CharField(default='', max_length=10, verbose_name='رمز المادة'),
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='الاسم الأول'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(choices=[('قران', 'قران'), ('تربية اسلامية', 'تربية اسلامية'), ('لغتي', 'لغتي'), ('رياضيات', 'رياضيات'), ('علوم', 'علوم'), ('تربية بدنية', 'تربية بدنية'), ('تربية فنية', 'تربية فنية'), ('لغة انجليزية', 'لغة انجليزية'), ('اجتماعيات', 'اجتماعيات'), ('مهارات حيايتة وأسرية', 'مهارات حيايتة وأسرية'), ('التربية الرقمية', 'التربية الرقمية')], max_length=255, verbose_name='المادة'),
        ),
        migrations.RemoveField(
            model_name='subject',
            name='teacher',
        ),
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.teacher'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='major',
            field=models.CharField(choices=[('قران', 'قران'), ('تربية اسلامية', 'تربية اسلامية'), ('لغتي', 'لغتي'), ('رياضيات', 'رياضيات'), ('علوم', 'علوم'), ('تربية بدنية', 'تربية بدنية'), ('تربية فنية', 'تربية فنية'), ('لغة انجليزية', 'لغة انجليزية'), ('اجتماعيات', 'اجتماعيات'), ('مهارات حيايتة وأسرية', 'مهارات حيايتة وأسرية'), ('التربية الرقمية', 'التربية الرقمية')], max_length=100, null=True, verbose_name='الاسم الأول'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='الاسم الأول'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='اسم العائلة'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mid_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='اسم الأب'),
        ),
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('الأول ابتدائي', 'الأول ابتدائي'), ('الثاني ابتدائي', 'الثاني ابتدائي'), ('الثالث ابتدائي', 'الثالث ابتدائي'), ('الرابع ابتدائي', 'الرابع ابتدائي'), ('الخامس ابتدائي', 'الخامس ابتدائي'), ('السادس ابتدائي', 'السادس ابتدائي'), ('الأول متوسط', 'الأول متوسط'), ('الثاني متوسط', 'الثاني متوسط'), ('الثالث متوسط', 'الثالث متوسط'), ('الأول ثانوي', 'الأول ثانوي'), ('الثاني ثانوي', 'الثاني ثانوي'), ('الثالث ثانوي', 'الثالث ثانوي')], max_length=150, verbose_name='الصف')),
                ('section', models.CharField(choices=[('أ', 'أ'), ('ب', 'ب'), ('ج', 'ج'), ('د', 'د')], max_length=2, verbose_name='الشعبة')),
                ('students', models.ManyToManyField(related_name='classes', to='app.Student')),
            ],
            options={
                'verbose_name': 'الفصل',
                'verbose_name_plural': 'الفصول',
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='class_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.classgroup'),
        ),
        migrations.AlterField(
            model_name='course',
            name='which_class',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.classgroup'),
        ),
        migrations.DeleteModel(
            name='Classes',
        ),
    ]
