# Generated by Django 3.2.17 on 2023-04-20 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_classgroup_class_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classgroup',
            name='class_time',
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_time', models.CharField(choices=[('1', 'الحصة الأولى'), ('2', 'الحصة الثانية'), ('3', 'الحصة الثالثة'), ('4', 'الحصة الرابعة'), ('5', 'الحصة الخامسة'), ('6', 'الحصة السادسة'), ('7', 'الحصة السابعة'), ('8', 'الحصة الثامنة'), ('9', 'الحصة التاسعة')], max_length=150, null=True)),
                ('class_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.classgroup')),
                ('class_subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.subject')),
            ],
            options={
                'verbose_name': 'الحصة الدراسية',
                'verbose_name_plural': 'الحصص الدراسية',
            },
        ),
    ]
