# Generated by Django 3.2.17 on 2023-04-21 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20230420_2338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quizzes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='اختبار جديد', max_length=150, null=True, verbose_name='عنوان الاختبار')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.course')),
            ],
            options={
                'verbose_name': 'الاختبار',
                'verbose_name_plural': 'الاختبارات',
                'ordering': ['course'],
            },
        ),
    ]
