# Generated by Django 3.2.17 on 2023-04-22 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('technique', models.IntegerField(choices=[(0, 'Multiple Choice')], default=0, verbose_name='Type of Question')),
                ('difficulty', models.IntegerField(choices=[(0, 'Fundamental'), (1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced'), (4, 'Expert')], default=0, verbose_name='Difficulty')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False, verbose_name='Active Status')),
                ('quiz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question', to='app.quizzes')),
            ],
            options={
                'verbose_name': 'السؤال',
                'verbose_name_plural': 'الاسئلة',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='my_column',
            field=models.ManyToManyField(blank=True, choices=[('عصف ذهني', 'عصف ذهني'), ('خرائط ذهنية', 'خرائط ذهنية'), ('الصف المقلوب', 'الصف المقلوب'), ('التعلم التعاوني', 'التعلم التعاوني'), ('التعلم الذاتي', 'التعلم الذاتي'), ('التجارب', 'التجارب')], related_name='related_column', to='app.Course'),
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
    ]
