# Generated by Django 3.2.17 on 2023-04-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20230422_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='my_column',
            field=models.ManyToManyField(blank=True, choices=[('عصف ذهني', 'عصف ذهني'), ('خرائط ذهنية', 'خرائط ذهنية'), ('الصف المقلوب', 'الصف المقلوب'), ('التعلم التعاوني', 'التعلم التعاوني'), ('التعلم الذاتي', 'التعلم الذاتي'), ('التجارب', 'التجارب')], related_name='الاستراتيجية', to='app.Course'),
        ),
    ]
