# Generated by Django 3.2.17 on 2023-04-23 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20230423_1151'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClassGroup',
            new_name='Class',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
