# Generated by Django 3.2.17 on 2023-04-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20230423_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='class_day',
            field=models.DateField(null=True),
        ),
    ]
