# Generated by Django 3.2.17 on 2023-04-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_schoolclass_class_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolclass',
            name='class_day',
            field=models.CharField(choices=[(1, 'الأحد'), (2, 'الأثنين'), (3, 'الثلاثاء'), (4, 'الأربعاء'), (5, 'الخميس')], max_length=50, null=True),
        ),
    ]
