# Generated by Django 3.2.17 on 2023-04-23 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_alter_schoolclass_class_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolclass',
            name='class_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='الصف', to='app.class'),
        ),
    ]
