# Generated by Django 3.2.17 on 2023-04-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_alter_schoolclass_class_day'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolclass',
            options={'ordering': ['class_time'], 'verbose_name': 'الحصة الدراسية', 'verbose_name_plural': 'الحصص الدراسية'},
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='class_day',
            field=models.CharField(choices=[('0', 'الأحد'), ('1', 'الأثنين'), ('2', 'الثلاثاء'), ('3', 'الأربعاء'), ('4', 'الخميس')], max_length=50),
        ),
    ]
