# Generated by Django 3.2.17 on 2023-04-24 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_auto_20230423_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Updated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_updated', models.DateTimeField(auto_now_add=True, verbose_name='آخر تحديث')),
            ],
        ),
        migrations.AlterModelOptions(
            name='assignment',
            options={'verbose_name': 'الواجب - Assignment', 'verbose_name_plural': 'الواجبات - Assignments'},
        ),
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name': 'الفصل - Class', 'verbose_name_plural': 'الفصول - Classes'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'الدرس - Course', 'verbose_name_plural': 'الدروس - Courses'},
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'verbose_name': 'درجة الواجب - Assignment Grade', 'verbose_name_plural': 'درجة الواجبات - Assignments Grades'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['id'], 'verbose_name': 'السؤال - Question', 'verbose_name_plural': 'الاسئلة - Questions'},
        ),
        migrations.AlterModelOptions(
            name='quizzes',
            options={'ordering': ['course'], 'verbose_name': 'الاختبار - Quiz', 'verbose_name_plural': 'الاختبارات - Quizzes'},
        ),
        migrations.AlterModelOptions(
            name='schoolclass',
            options={'ordering': ['class_day'], 'verbose_name': 'School Class - الحصة الدراسية', 'verbose_name_plural': 'الحصص الدراسية -  School Classes '},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'الطالب - Student', 'verbose_name_plural': 'الطلاب - Students'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'المادة الدراسية - Subject', 'verbose_name_plural': 'المواد الدراسية - Subjects'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'المعلم- Teacher', 'verbose_name_plural': 'المعلمون- Teachers'},
        ),
    ]
