# Generated by Django 3.2.17 on 2023-04-24 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_auto_20230424_2228'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Updated',
        ),
    ]
