# Generated by Django 3.2.17 on 2023-04-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('1', 'الحصة الأولى'), ('2', 'الحصة الثانية'), ('3', 'الحصة الثالثة'), ('4', 'الحصة الرابعة'), ('5', 'الحصة الخامسة'), ('6', 'الحصة السادسة'), ('7', 'الحصة السابعة'), ('8', 'الحصة الثامنة'), ('9', 'الحصة التاسعة')], max_length=150)),
                ('day', models.CharField(choices=[('0', 'الأحد'), ('1', 'الأثنين'), ('2', 'الثلاثاء'), ('3', 'الأربعاء'), ('4', 'الخميس')], max_length=50)),
                ('time', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'الحصة',
                'verbose_name_plural': 'الحصص',
            },
        ),
    ]
