# Generated by Django 3.2.17 on 2023-04-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_alter_timetable_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='time',
        ),
        migrations.AddField(
            model_name='timetable',
            name='ending',
            field=models.TimeField(null=True, verbose_name='نهاية الحصة'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='starting',
            field=models.TimeField(null=True, verbose_name='بداية الحصة'),
        ),
    ]
