# Generated by Django 3.2.17 on 2023-04-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_auto_20230425_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='day',
            field=models.CharField(choices=[('0', 'الأحد'), ('1', 'الأثنين'), ('2', 'الثلاثاء'), ('3', 'الأربعاء'), ('4', 'الخميس')], max_length=50, verbose_name='اليوم'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='title',
            field=models.CharField(choices=[('1', 'الحصة الأولى'), ('2', 'الحصة الثانية'), ('3', 'الحصة الثالثة'), ('4', 'الحصة الرابعة'), ('5', 'الحصة الخامسة'), ('6', 'الحصة السادسة'), ('7', 'الحصة السابعة'), ('8', 'الحصة الثامنة'), ('9', 'الحصة التاسعة')], max_length=150, verbose_name='الحصة'),
        ),
    ]
