# Generated by Django 3.2.17 on 2023-04-25 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_auto_20230425_1319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolclass',
            options={'ordering': ['class_time'], 'verbose_name': 'School Class - الحصة الدراسية', 'verbose_name_plural': 'الحصص الدراسية -  School Classes '},
        ),
        migrations.AlterModelOptions(
            name='timetable',
            options={'ordering': ['day', 'starting'], 'verbose_name': 'الحصة', 'verbose_name_plural': 'الحصص'},
        ),
        migrations.RemoveField(
            model_name='schoolclass',
            name='class_day',
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='class_time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.timetable'),
        ),
    ]
