# Generated by Django 3.2.17 on 2023-04-26 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_auto_20230425_1349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classtime',
            options={'ordering': ['title', 'starting'], 'verbose_name': 'الحصة', 'verbose_name_plural': 'الحصص'},
        ),
        migrations.AlterModelOptions(
            name='timetable',
            options={'ordering': ['day'], 'verbose_name': 'جدول الحصص', 'verbose_name_plural': 'جدول الحصص'},
        ),
        migrations.AlterField(
            model_name='timetable',
            name='class_time',
            field=models.ManyToManyField(related_name='class_time', to='app.ClassTime'),
        ),
    ]
