# Generated by Django 3.2.17 on 2023-04-26 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_auto_20230426_0747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='class_group',
        ),
    ]
