# Generated by Django 3.2.17 on 2023-04-27 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_auto_20230427_0506'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.user')),
                ('date_of_birth', models.DateField()),
            ],
            options={
                'verbose_name': 'الطالب - Student',
                'verbose_name_plural': 'الطلاب - Students',
                'ordering': ['first_name'],
            },
            bases=('app.user',),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.user')),
                ('major', models.CharField(choices=[('قران', 'قران'), ('تربية اسلامية', 'تربية اسلامية'), ('لغتي', 'لغتي'), ('رياضيات', 'رياضيات'), ('علوم', 'علوم'), ('تربية بدنية', 'تربية بدنية'), ('تربية فنية', 'تربية فنية'), ('لغة انجليزية', 'لغة انجليزية'), ('اجتماعيات', 'اجتماعيات'), ('مهارات حيايتة وأسرية', 'مهارات حيايتة وأسرية'), ('التربية الرقمية', 'التربية الرقمية')], max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'المعلم - Teacher',
                'verbose_name_plural': 'المعلمون - Teachers',
                'ordering': ['first_name'],
            },
            bases=('app.user',),
        ),
    ]
