# Generated by Django 4.1.7 on 2023-04-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_auto_20230428_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('1', 'الحصةالأولى'), ('2', 'الحصةالثانية'), ('3', 'الحصةالثالثة'), ('4', 'الحصةالرابعة'), ('5', 'الحصةالخامسة'), ('6', 'الحصةالسادسة'), ('7', 'الحصةالسابعة'), ('8', 'الحصةالثامنة')], max_length=150, verbose_name='الحصة')),
                ('start_at', models.TimeField(verbose_name='بداية الحصة')),
                ('end_at', models.TimeField(verbose_name='نهاية الحصة')),
            ],
            options={
                'verbose_name': 'الحصة',
                'verbose_name_plural': 'الحصص',
            },
        ),
    ]
