# Generated by Django 4.1.7 on 2023-04-30 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_alter_class_options_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='gender',
            field=models.CharField(choices=[('Male', 'بنين'), ('Female', 'بنات')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(choices=[('قران', 'قران'), ('تربية اسلامية', 'تربية اسلامية'), ('لغتي', 'لغتي'), ('رياضيات', 'رياضيات'), ('علوم', 'علوم'), ('تربية بدنية', 'تربية بدنية'), ('تربية فنية', 'تربية فنية'), ('لغة انجليزية', 'لغة انجليزية'), ('اجتماعيات', 'اجتماعيات'), ('مهارات حيايتة وأسرية', 'مهارات حيايتة وأسرية'), ('التربية الرقمية', 'التربية الرقمية')], max_length=150, verbose_name='المادة'),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('1', 'الأحد'), ('2', 'الأثنين'), ('3', 'الثلاثاء'), ('4', 'الأربعاء'), ('5', 'الخميس')], max_length=50, null=True)),
                ('class_is', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='app.class')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.subject')),
            ],
            options={
                'verbose_name': 'الجدول',
                'verbose_name_plural': 'الجدول',
                'ordering': ['day', 'class_is'],
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('1', 'الأول ابتدائي'), ('2', 'الثاني ابتدائي'), ('3', 'الثالث ابتدائي'), ('4', 'الرابع ابتدائي'), ('5', 'الخامس ابتدائي'), ('6', 'السادس ابتدائي'), ('7', 'الأول متوسط'), ('8', 'الثاني متوسط'), ('9', 'الثالث متوسط'), ('10', 'الأول ثانوي'), ('11', 'الثاني ثانوي'), ('12', 'الثالث ثانوي')], max_length=150, null=True)),
                ('section', models.CharField(choices=[('1', 'الأول ابتدائي'), ('2', 'الثاني ابتدائي'), ('3', 'الثالث ابتدائي'), ('4', 'الرابع ابتدائي'), ('5', 'الخامس ابتدائي'), ('6', 'السادس ابتدائي'), ('7', 'الأول متوسط'), ('8', 'الثاني متوسط'), ('9', 'الثالث متوسط'), ('10', 'الأول ثانوي'), ('11', 'الثاني ثانوي'), ('12', 'الثالث ثانوي')], max_length=150, null=True)),
                ('student', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.student')),
            ],
            options={
                'verbose_name': 'الفصل',
                'verbose_name_plural': 'الفصول',
                'ordering': ['name', 'section'],
            },
        ),
    ]
