# Generated by Django 4.1.7 on 2023-04-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_school_gender_alter_subject_name_lesson_classroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='section',
            field=models.CharField(choices=[('1', 'أ'), ('2', 'ب'), ('3', 'ج'), ('4', 'د')], max_length=150, null=True),
        ),
    ]
