# Generated by Django 4.1.7 on 2023-04-30 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_alter_classroom_section'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['first_name'], 'verbose_name': 'الطالب ', 'verbose_name_plural': 'الطلاب'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['first_name'], 'verbose_name': 'المعلم', 'verbose_name_plural': 'المعلمون'},
        ),
    ]
