# Generated by Django 4.1.7 on 2023-05-01 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_alter_student_options_alter_teacher_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='student',
        ),
        migrations.AddField(
            model_name='classroom',
            name='student',
            field=models.ManyToManyField(null=True, to='app.student'),
        ),
    ]
