# Generated by Django 4.1.7 on 2023-05-02 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_alter_classroom_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Classroom',
            new_name='Grade',
        ),
    ]
