# Generated by Django 4.1.7 on 2023-05-02 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0062_alter_grade_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='grade_is',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='app.class', unique=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='class_is',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.class'),
        ),
    ]
