# Generated by Django 4.1.7 on 2023-05-02 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_alter_lesson_grade_is'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['name'], 'verbose_name': 'الحصة', 'verbose_name_plural': 'اوقات الحصص'},
        ),
    ]
