# Generated by Django 4.1.7 on 2023-05-02 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0065_alter_class_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['day', 'class_is'], 'verbose_name': 'الحصة الدراسية', 'verbose_name_plural': 'الحصص الدراسية'},
        ),
    ]
